### ISSUE TITLE
directionality of pli_multitaper_max_fs-1_fmin-0_fmax-0-5

### ISSUE THREAD

**Issue by anniegbryant** [DynamicsAndNeuralSystems/pyspi#14]
Hi Oliver,

Just wondering about the directionality of the SPI "pli_multitaper_max_fs-1_fmin-0_fmax-0-5"? In the pyspi manuscript, it's listed as undirected. However, in my dataset, I found that observation_1 --> observation_2 has a different value from observation_2 --> observation_1. Can you please clarify whether this feature is undirected or directed?

Thank you :)

**Comment by olivercliff** [comment]
Hi Annie, this measure is derived from the [spectral_connectivity](https://github.com/Eden-Kramer-Lab/spectral_connectivity) toolbox and should be undirected.

Are you able to send the data you're using and I'll double check there's nothing wrong on this end before sending the issue over?

**Comment by anniegbryant** [comment]
[example_dataset.zip](https://github.com/olivercliff/pyspi/files/8812267/example_dataset.zip)

Sure, I've added an example dataset in which the values were different depending on direction here as a zipped .npy matrix.

**Comment by olivercliff** [comment]
OK I just had a look and you're definitely right -- the PLI statistics (and some related stats) are asymmetric. I'll open an issue on the original repository.
