### ISSUE TITLE
Could you please provide more details about the config.ymal file?

### ISSUE THREAD

**Issue by ChenK19** [DynamicsAndNeuralSystems/pyspi#37]
Hi, 
We are trying to analyse some neural time-series data, pyspi is a excellent job in my opinion.
However we meet some problems for the unclear parts of the document, could you provide more illustration in documentation?

(1) For the transfer entropy,  and Mutualinfo or other jpype1's  content, the sub content like prop_k, k_history, l_history is different from idtxl's documentation, [https://pwollstadt.github.io/IDTxl/html/index.html](url).
(2) For some other simple SPI, what;s the meaning of statistic:max\min?

If you could include more descriptions of these things (and more details) in the documentation,then we can get a lot of help.
Very thanks for your any reply!

**Comment by joshuabmoore** [comment]
Hi @ChenK19, 
The pyspi documentation has recently been updated to include descriptions of all the SPIs currently included in the toolkit. This includes details regarding their specific implementation and explanations of the various estimators. You can access the docs [here]([time-series-features.gitbook.io/pyspi/](https://time-series-features.gitbook.io/pyspi/)). I hope you find this useful! 
Feel free to ping us if you have any further questions.
