### ISSUE TITLE
Can't install pyspi - missing pyEDM==1.9.3

### ISSUE THREAD

**Issue by Hananel-Hazan** [DynamicsAndNeuralSystems/pyspi#41]
Thank you of the great package. 

Trying to install `pyspi` under Ubuntu using 'pip'. After cloning the repository and running `pip install .` from the pyspi derectory, the setup stop with the following error:

```
INFO: pip is looking at multiple versions of pyspi to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement pyEDM==1.9.3 (from pyspi) (from versions: 1.0.1, 1.0.3, 1.0.3.2, 1.10.1.1, 1.10.2.0, 1.10.3.0, 1.11.0.0, 1.12.0.0, 1.12.1.0, 1.12.2.0, 1.13.0.0, 1.13.1.0, 1.14.0.0, 1.14.0.1, 1.14.0.2, 1.14.2.0, 1.14.3.0, 1.15.0.0, 1.15.0.3, 1.15.0.4, 1.15.1.0)
ERROR: No matching distribution found for pyEDM==1.9.3
```

According to [pypi.org](https://pypi.org/project/pyEDM/) the newest pyEDM version is 1.15.1.0  released: Oct 28, 2023 

Where I can find pyEDM==1.9.3?

Thanks

**Comment by anniegbryant** [comment]
Hi Hananel-Hazan, sorry for the delayed reply and for the installation bug. Some operating systems/pip versions seem unable to locate pyEDM==1.9.3 -- MacOS seems to find it ok, but I remember the same issue on my Ubuntu VM. In that case, the workaround is to download and install the wheel locally as follows:

1. Download the wheel file (.whl) from the pyEDM repository for version 1.9.3 at the following link (one of the two Linux versions depending on whether you're running i686 or x86_64 architecture): https://pypi.org/project/pyEDM/1.9.3.0/#files
2. Install the `wheel` package if you don't already have it with `pip install wheel`.
3. Navigate in your terminal to where you've downloaded the wheel file. 
4. Install the wheel file directly with the command `pip install [file.whl]`. For example, that might look like `pip install 
pyEDM-1.9.3.0-cp39-cp39-manylinux2010_x86_64.whl`.

That should get pyEDM==1.9.3 installed okay on your machine to satisfy `pyspi` requirements, but ping us back if you run into any further issues!

**Comment by Hananel-Hazan** [comment]
Thank you for your response, now that I see your answer, I think that the reason `pip` didn't find pyEDM version 1.9.3 is because I am using python `3.11` and not an older version of python. That mean that I need to find an alternative to this issue since my other scripts that use `pyspi` require python `>=3.10`

Quick question, can `pyspi` can use newer version of pyEDM, or that will brake `pyspi`
