### ISSUE TITLE
ModuleNotFoundError `sktime`

### ISSUE THREAD

**Issue by jajcayn** [DynamicsAndNeuralSystems/pyspi#5]
Hey!

Great preprint! I am really interested in trying out the package. However, when I installed it, I cannot import `Calculator`, nor run the tests with `pytest`. I am getting:
```
ModuleNotFoundError: No module named 'sktime.utils.data_io'
```
I have `sktime` installed and can import it without any problems.
Thanks for looking into it!

N.

**Comment by olivercliff** [comment]
Hi,

That was due to a change in `sktime > 0.8.0`. It should be fixed in the latest version of the code.
